/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// By default, Docusaurus generates a sidebar from the docs folder structure
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  /*
  openApiSidebar: [
    {
      type: "category",
      label: "Pooler API",
      link: {
        type: "generated-index",
        title: "Pooler API",
        description:
          "Pooler API.",
        slug: "/category/pooler-api"
      },
      // @ts-ignore
      items: require("./docs/api/sidebar.js")
    }
  ],
  */
 /*
  introSidebar: [
    {
      type: 'category',
      label: 'Docs',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'API',
      items: ['api/intro'],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API',
      items: ['api/intro'],
    },
  ],
  //*/
};

module.exports = sidebars;
