openapi: 3.0.0
info:
  title: Pooler API
  version: 1.0.0
servers:
  - url: https://uniswapv2-ethindia.powerloom.io/api/
    description: Uniswap V2
  - url: https://quickswap.powerloom.io/api/
    description: Quickswap
  - url: https://sushiswap.powerloom.io/api/
    description: Sushiswap 
paths:
  /snapshots/{pair_contract_address}:
    get:
      summary: Get Past Snapshots
      operationId: get_past_snapshots_snapshots__pair_contract_address__get
      parameters:
        - required: true
          schema:
            title: Pair Contract Address
            type: string
          name: pair_contract_address
          in: path
        - required: false
          schema:
            title: Maxcount
            type: integer
          name: maxCount
          in: query
        - required: false
          schema:
            title: Data
            type: string
            default: 'false'
          name: data
          in: query
        - required: false
          schema:
            title: Stream
            type: string
            default: pair_total_reserves
          name: stream
          in: query
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /pair_address:
    get:
      summary: Get Pair Contract From Tokens
      operationId: get_pair_contract_from_tokens_pair_address_get
      parameters:
        - required: true
          schema:
            title: Token0
            type: string
          name: token0
          in: query
        - required: true
          schema:
            title: Token1
            type: string
          name: token1
          in: query
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-pair/{pair_contract_address}:
    get:
      summary: Get Single V2 Pair Data
      operationId: get_single_v2_pair_data_v2_pair__pair_contract_address__get
      parameters:
        - required: true
          schema:
            title: Pair Contract Address
            type: string
          name: pair_contract_address
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-pairs:
    get:
      summary: Get V2 Pairs Data
      operationId: get_v2_pairs_data_v2_pairs_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/api/v2-pairs:
    get:
      summary: Get V2 Pairs Data
      operationId: get_v2_pairs_data_v1_api_v2_pairs_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v2-pairs/snapshots:
    get:
      summary: Get V2 Pairs Snapshots
      operationId: get_v2_pairs_snapshots_v2_pairs_snapshots_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/api/v2-pairs/snapshots:
    get:
      summary: Get V2 Pairs Snapshots
      operationId: get_v2_pairs_snapshots_v1_api_v2_pairs_snapshots_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v2-pairs/{block_height}:
    get:
      summary: Get V2 Pairs At Block Height
      operationId: get_v2_pairs_at_block_height_v2_pairs__block_height__get
      parameters:
        - required: true
          schema:
            title: Block Height
            type: integer
          name: block_height
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/api/v2-pairs/{block_height}:
    get:
      summary: Get V2 Pairs At Block Height
      operationId: get_v2_pairs_at_block_height_v1_api_v2_pairs__block_height__get
      parameters:
        - required: true
          schema:
            title: Block Height
            type: integer
          name: block_height
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-daily-stats/snapshots:
    get:
      summary: Get V2 Daily Stats Snapshot
      operationId: get_v2_daily_stats_snapshot_v2_daily_stats_snapshots_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/api/v2-daily-stats/snapshots:
    get:
      summary: Get V2 Daily Stats Snapshot
      operationId: get_v2_daily_stats_snapshot_v1_api_v2_daily_stats_snapshots_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v2-daily-stats/{block_height}:
    get:
      summary: Get V2 Daily Stats By Block
      operationId: get_v2_daily_stats_by_block_v2_daily_stats__block_height__get
      parameters:
        - required: true
          schema:
            title: Block Height
            type: integer
          name: block_height
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/api/v2-daily-stats/{block_height}:
    get:
      summary: Get V2 Daily Stats By Block
      operationId: get_v2_daily_stats_by_block_v1_api_v2_daily_stats__block_height__get
      parameters:
        - required: true
          schema:
            title: Block Height
            type: integer
          name: block_height
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-pairs-recent-logs:
    get:
      summary: Get V2 Pairs Recent Logs
      operationId: get_v2_pairs_recent_logs_v2_pairs_recent_logs_get
      parameters:
        - required: true
          schema:
            title: Pair Contract
            type: string
          name: pair_contract
          in: query
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-tokens-recent-logs:
    get:
      summary: Get V2 Tokens Recent Logs
      operationId: get_v2_tokens_recent_logs_v2_tokens_recent_logs_get
      parameters:
        - required: true
          schema:
            title: Token Contract
            type: string
          name: token_contract
          in: query
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-token/{token_addr}:
    get:
      summary: Get Single Token Aggregate Data
      operationId: get_single_token_aggregate_data_v2_token__token_addr__get
      parameters:
        - required: true
          schema:
            title: Token Addr
            type: string
          name: token_addr
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-tokens:
    get:
      summary: Get V2 Tokens
      operationId: get_v2_tokens_v2_tokens_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/api/v2-tokens:
    get:
      summary: Get V2 Tokens
      operationId: get_v2_tokens_v1_api_v2_tokens_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v2-tokens/snapshots:
    get:
      summary: Get V2 Tokens Snapshots
      operationId: get_v2_tokens_snapshots_v2_tokens_snapshots_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/api/v2-tokens/snapshots:
    get:
      summary: Get V2 Tokens Snapshots
      operationId: get_v2_tokens_snapshots_v1_api_v2_tokens_snapshots_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v2-tokens/{block_height}:
    get:
      summary: Get V2 Tokens Data By Block
      operationId: get_v2_tokens_data_by_block_v2_tokens__block_height__get
      parameters:
        - required: true
          schema:
            title: Block Height
            type: integer
          name: block_height
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/api/v2-tokens/{block_height}:
    get:
      summary: Get V2 Tokens Data By Block
      operationId: get_v2_tokens_data_by_block_v1_api_v2_tokens__block_height__get
      parameters:
        - required: true
          schema:
            title: Block Height
            type: integer
          name: block_height
          in: path
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v2-daily-stats:
    get:
      summary: Get V2 Pairs Daily Stats
      operationId: get_v2_pairs_daily_stats_v2_daily_stats_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/api/v2-daily-stats:
    get:
      summary: Get V2 Pairs Daily Stats
      operationId: get_v2_pairs_daily_stats_v1_api_v2_daily_stats_get
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-Key
      in: header
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
